title: Rosemary Dorsey
description: An Astronomy PhD Student at the University of Canterbury, New Zealand.
![RCD_MountJohn_2019](https://user-images.githubusercontent.com/65519533/91275789-ba208d80-e7d4-11ea-9da6-d2ba8aef279c.jpg)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
