title: Rosemary Dorsey
description: Astronomy PhD Student at the University of Canterbury, New Zealand  Email: rosemary.dorsey@pg.canterbury.ac.nz
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
logo: assets/images/RCD_MountJohn_2019_Circle.png
